# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# Project
version=0.1.0
group=io.github.cherrybxrry.inflatablemobgirls
java_version=25
# Common
minecraft_version=26.2
mod_name=Inflatable Mob Girls
mod_author=CherryBxrry
mod_id=inflatablemobgirls
license=MIT
credits=bARTek
description=NOT AN OFFICIAL MINECRAFT MOD. NOT APPROVED BY OR ASSOCIATED WITH MOJANG OR MICROSOFT! A mod that adds tameable, inflatable mob girls to your game. Credit to bARTek for both the creeper girl and the ghast girl models.
website=https://github.com/CherryBxrry/InflatableMobGirls
issue_tracker=https://github.com/CherryBxrry/InflatableMobGirls/issues
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2
# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3
# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.48-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
